import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState(() => localStorage.getItem('globalLang') || 'en');

  useEffect(() => {
    localStorage.setItem('globalLang', currentLanguage);
  }, [currentLanguage]);

  const t = (key) => {
    return translations[currentLanguage]?.[key] || translations['en']?.[key] || key;
  };

  const languageOptions = [
    { code: 'en', label: 'English (EN)' },
    { code: 'es', label: 'Español (ES)' },
    { code: 'fr', label: 'Français (FR)' },
    { code: 'de', label: 'Deutsch (DE)' },
    { code: 'zh', label: '中文 (ZH)' },
    { code: 'ja', label: '日本語 (JA)' },
    { code: 'si', label: 'සිංහල (SI)' },
    { code: 'ta', label: 'தமிழ் (TA)' },
  ];

  return (
    <LanguageContext.Provider value={{ currentLanguage, setCurrentLanguage, t, languageOptions }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations = {
  en: {
    // Sidebar
    sidebarCore: "Core Dashboard",
    sidebarOverview: "Global Overview",
    sidebarAssets: "Asset Registry",
    sidebarPersonnel: "Personnel",
    sidebarUsers: "User Accounts",
    sidebarSecurity: "Cyber Security (SOC)",
    sidebarCompliance: "Compliance Center",
    sidebarThreats: "Threat Matrix",
    sidebarAI: "AI Risk Engine",
    sidebarTracking: "Smart Tracking",
    sidebarLive: "Live Device Health",
    sidebarGeo: "Geo-Location Tracking",
    sidebarQR: "QR / Barcode Scan",
    sidebarOperations: "Operations",
    sidebarMaintenance: "Maintenance Logs",
    sidebarReports: "Data Extraction",
    sidebarAudit: "Audit Log",
    sidebarSettings: "System Config",
    sidebarLogout: "TERMINATE SESSION",
    // Topbar
    topbarSearch: "Search assets, IP, IDs...",
    topbarUplink: "Uplink Status",
    topbarSecure: "SECURE",
    topbarSystemAlerts: "System Alerts",
    topbarMarkRead: "MARK ALL READ",
    topbarViewLogs: "View All Logs →",
    // Asset registry financials
    title: "Value Loss & Replacement Forecast",
    sub: "Dynamic calculations: Even Decline vs Accelerated Decline",
    year1: "Year 1 Estimated Replacement Cost",
    year2: "Year 2 Estimated Replacement Cost",
    year3: "Year 3 Estimated Replacement Cost",
    evenDecline: "Even Annual Decline Value",
    accDecline: "Accelerated Decline Value",
    purchaseCost: "Purchase Cost",
    ageLifespan: "Age / Lifespan",
    lifecycleStatus: "Lifecycle Status",
    activeSecure: "ACTIVE & SECURE",
    replaceNow: "REPLACE NOW",
    warrantyExpired: "WARRANTY EXPIRED",
    settingsTitle: "SETTINGS FOR FUTURE BUDGET CALCULATIONS",
    resetSettings: "Reset to Default Settings",
    exportReport: "EXPORT REPORT",
    noEntries: "No financial entries found.",
    currencyLabel: "Currency",
    langLabel: "Language",
    optExcludeRetired: "Exclude Retired Assets from calculations",
    optStrictDep: "Strict straight-line depreciation (0% salvage floor)",
    optOnlyDue: "Show only assets requiring replacement",
    yearsShort: "yrs"
  },
  es: {
    sidebarCore: "Panel Principal",
    sidebarOverview: "Resumen Global",
    sidebarAssets: "Registro de Activos",
    sidebarPersonnel: "Personal",
    sidebarUsers: "Cuentas de Usuario",
    sidebarSecurity: "Ciberseguridad (SOC)",
    sidebarCompliance: "Centro de Cumplimiento",
    sidebarThreats: "Matriz de Amenazas",
    sidebarAI: "Motor de Riesgo IA",
    sidebarTracking: "Seguimiento Inteligente",
    sidebarLive: "Estado del Dispositivo",
    sidebarGeo: "Seguimiento GPS",
    sidebarQR: "Escanear QR",
    sidebarOperations: "Operaciones",
    sidebarMaintenance: "Registro de Mantenimiento",
    sidebarReports: "Extracción de Datos",
    sidebarAudit: "Registro de Auditoría",
    sidebarSettings: "Configuración",
    sidebarLogout: "CERRAR SESIÓN",
    topbarSearch: "Buscar activos, IP, IDs...",
    topbarUplink: "Estado del enlace",
    topbarSecure: "SEGURO",
    topbarSystemAlerts: "Alertas del Sistema",
    topbarMarkRead: "MARCAR LEÍDO",
    topbarViewLogs: "Ver registros →",
    title: "Pérdida de Valor y Pronóstico",
    sub: "Cálculo dinámico: Amortización Lineal vs Acelerada",
    year1: "Costo Estimado de Reemplazo - Año 1",
    year2: "Costo Estimado de Reemplazo - Año 2",
    year3: "Costo Estimado de Reemplazo - Año 3",
    evenDecline: "Valor de Amortización Lineal",
    accDecline: "Valor de Amortización Acelerada",
    purchaseCost: "Costo de Compra",
    ageLifespan: "Edad / Vida Útil",
    lifecycleStatus: "Estado de Ciclo de Vida",
    activeSecure: "ACTIVO Y SEGURO",
    replaceNow: "REEMPLAZAR AHORA",
    warrantyExpired: "GARANTÍA EXPIRADA",
    settingsTitle: "CONFIGURACIÓN PARA PRESUPUESTO",
    resetSettings: "Restablecer Ajustes",
    exportReport: "EXPORTAR REPORTE",
    noEntries: "No se encontraron registros financieros.",
    currencyLabel: "Moneda",
    langLabel: "Idioma",
    optExcludeRetired: "Excluir activos retirados de los cálculos",
    optStrictDep: "Amortización lineal estricta (0% residual)",
    optOnlyDue: "Mostrar solo activos por reemplazar",
    yearsShort: "años"
  },
  fr: {
    sidebarCore: "Tableau de Bord",
    sidebarOverview: "Vue Globale",
    sidebarAssets: "Registre des Actifs",
    sidebarPersonnel: "Personnel",
    sidebarUsers: "Comptes Utilisateurs",
    sidebarSecurity: "Cybersécurité (SOC)",
    sidebarCompliance: "Centre de Conformité",
    sidebarThreats: "Matrice des Menaces",
    sidebarAI: "Moteur de Risque IA",
    sidebarTracking: "Suivi Intelligent",
    sidebarLive: "Santé des Appareils",
    sidebarGeo: "Localisation GPS",
    sidebarQR: "Scanner QR",
    sidebarOperations: "Opérations",
    sidebarMaintenance: "Rapports de Maintenance",
    sidebarReports: "Extraction de Données",
    sidebarAudit: "Journal d'Audit",
    sidebarSettings: "Configuration",
    sidebarLogout: "FERMER LA SESSION",
    topbarSearch: "Rechercher actifs, IP, IDs...",
    topbarUplink: "Statut de liaison",
    topbarSecure: "SÉCURISÉ",
    topbarSystemAlerts: "Alertes Système",
    topbarMarkRead: "TOUT MARQUER LU",
    topbarViewLogs: "Voir tous les logs →",
    title: "Perte de Valeur & Prévisions",
    sub: "Calculs dynamiques : Linéaire vs Dégressif",
    year1: "Coût de Remplacement Estimé - An 1",
    year2: "Coût de Remplacement Estimé - An 2",
    year3: "Coût de Remplacement Estimé - An 3",
    evenDecline: "Valeur Déclin Linéaire",
    accDecline: "Valeur Déclin Dégressif",
    purchaseCost: "Coût d'Achat",
    ageLifespan: "Âge / Durée de Vie",
    lifecycleStatus: "Statut du Cycle de Vie",
    activeSecure: "ACTIF & SÉCURISÉ",
    replaceNow: "REMPLACER MAINTENANT",
    warrantyExpired: "GARANTIE EXPIRÉE",
    settingsTitle: "PARAMÈTRES DE BUDGET FUTUR",
    resetSettings: "Réinitialiser les Paramètres",
    exportReport: "EXPORTER LE RAPPORT",
    noEntries: "Aucune entrée financière trouvée.",
    currencyLabel: "Devise",
    langLabel: "Langue",
    optExcludeRetired: "Exclure les actifs retirés des calculs",
    optStrictDep: "Amortissement linéaire strict (0% résiduel)",
    optOnlyDue: "Afficher uniquement les actifs à remplacer",
    yearsShort: "ans"
  },
  de: {
    sidebarCore: "Übersicht",
    sidebarOverview: "Globale Ansicht",
    sidebarAssets: "Inventarliste",
    sidebarPersonnel: "Personal",
    sidebarUsers: "Benutzerkonten",
    sidebarSecurity: "Cybersecurity (SOC)",
    sidebarCompliance: "Compliance-Center",
    sidebarThreats: "Bedrohungsmatrix",
    sidebarAI: "KI-Risiko-Engine",
    sidebarTracking: "Smart-Tracking",
    sidebarLive: "Gerätestatus",
    sidebarGeo: "GPS-Ortung",
    sidebarQR: "QR-Code scannen",
    sidebarOperations: "Betrieb",
    sidebarMaintenance: "Wartungsprotokolle",
    sidebarReports: "Datenextraktion",
    sidebarAudit: "Audit-Log",
    sidebarSettings: "Systemkonfiguration",
    sidebarLogout: "SITZUNG BEENDEN",
    topbarSearch: "Assets, IPs, IDs suchen...",
    topbarUplink: "Verbindungsstatus",
    topbarSecure: "SICHER",
    topbarSystemAlerts: "Systemalarme",
    topbarMarkRead: "ALLE ALS GELESEN MARKIEREN",
    topbarViewLogs: "Alle Protokolle anzeigen →",
    title: "Wertverlust & Ersatzprognose",
    sub: "Dynamische Berechnung: Linearer vs. beschleunigter Wertverlust",
    year1: "Geschätzte Ersatzkosten - Jahr 1",
    year2: "Geschätzte Ersatzkosten - Jahr 2",
    year3: "Geschätzte Ersatzkosten - Jahr 3",
    evenDecline: "Linearer Abschreibungswert",
    accDecline: "Beschleunigter Abschreibungswert",
    purchaseCost: "Anschaffungskosten",
    ageLifespan: "Alter / Lebensdauer",
    lifecycleStatus: "Lebenszyklus-Status",
    activeSecure: "AKTIV & SICHER",
    replaceNow: "JETZT ERSETZEN",
    warrantyExpired: "GARANTIE ABGELAUFEN",
    settingsTitle: "EINSTELLUNGEN FÜR BUDGETBERECHNUNG",
    resetSettings: "Einstellungen zurücksetzen",
    exportReport: "BERICHT EXPORTIEREN",
    noEntries: "Keine Finanzeinträge gefunden.",
    currencyLabel: "Währung",
    langLabel: "Sprache",
    optExcludeRetired: "Ausgemusterte Assets ausschließen",
    optStrictDep: "Strikte lineare Abschreibung (0% Restwert)",
    optOnlyDue: "Nur zu ersetzende Assets anzeigen",
    yearsShort: "Jahre"
  },
  zh: {
    sidebarCore: "核心仪表板",
    sidebarOverview: "全局概览",
    sidebarAssets: "资产登记",
    sidebarPersonnel: "人员名册",
    sidebarUsers: "用户账户",
    sidebarSecurity: "网络安全 (SOC)",
    sidebarCompliance: "合规中心",
    sidebarThreats: "威胁矩阵",
    sidebarAI: "AI风险引擎",
    sidebarTracking: "智能追踪",
    sidebarLive: "实时设备健康",
    sidebarGeo: "GPS地理追踪",
    sidebarQR: "QR/条码扫描",
    sidebarOperations: "运营日志",
    sidebarMaintenance: "维护日志",
    sidebarReports: "数据提取",
    sidebarAudit: "审计日志",
    sidebarSettings: "系统配置",
    sidebarLogout: "结束会话",
    topbarSearch: "搜索资产、IP、ID...",
    topbarUplink: "上行链路状态",
    topbarSecure: "安全",
    topbarSystemAlerts: "系统警报",
    topbarMarkRead: "标记全部已读",
    topbarViewLogs: "查看所有日志 →",
    title: "价值折旧与更换预测",
    sub: "动态计算：直线折旧与加速折旧",
    year1: "第1年预计更换成本",
    year2: "第2年预计更换成本",
    year3: "第3年预计更换成本",
    evenDecline: "直线折旧值",
    accDecline: "加速折旧值",
    purchaseCost: "采购成本",
    ageLifespan: "账龄 / 使用寿命",
    lifecycleStatus: "生命周期状态",
    activeSecure: "运行中且安全",
    replaceNow: "立即更换",
    warrantyExpired: "保修期已过",
    settingsTitle: "未来预算计算设置",
    resetSettings: "重置为默认设置",
    exportReport: "导出报告",
    noEntries: "未找到财务记录。",
    currencyLabel: "货币",
    langLabel: "语言",
    optExcludeRetired: "计算中排除已退役资产",
    optStrictDep: "严格直线折旧（0%残值限额）",
    optOnlyDue: "仅显示需要更换的资产",
    yearsShort: "年"
  },
  ja: {
    sidebarCore: "ダッシュボード",
    sidebarOverview: "全体概要",
    sidebarAssets: "資産台帳",
    sidebarPersonnel: "人员名簿",
    sidebarUsers: "ユーザー管理",
    sidebarSecurity: "サイバーセキュリティ (SOC)",
    sidebarCompliance: "コンプライアンス",
    sidebarThreats: "脅威マトリクス",
    sidebarAI: "AIリスク分析",
    sidebarTracking: "スマート追跡",
    sidebarLive: "稼働状態監視",
    sidebarGeo: "GPS位置追跡",
    sidebarQR: "QRコードスキャン",
    sidebarOperations: "業務管理",
    sidebarMaintenance: "保守記録",
    sidebarReports: "データ抽出",
    sidebarAudit: "監査ログ",
    sidebarSettings: "システム設定",
    sidebarLogout: "セッション終了",
    topbarSearch: "資産、IP、IDで検索...",
    topbarUplink: "接続状態",
    topbarSecure: "安全",
    topbarSystemAlerts: "システムアラート",
    topbarMarkRead: "すべて既読にする",
    topbarViewLogs: "すべてのログを表示 →",
    title: "資産減価償却と更新予測",
    sub: "動的計算：定額法 vs 定率法",
    year1: "1年目の見積更新費用",
    year2: "2年目の見積更新費用",
    year3: "3年目の見積更新費用",
    evenDecline: "定額償却価格",
    accDecline: "定率償却価格",
    purchaseCost: "購入コスト",
    ageLifespan: "経過年数 / 耐用年数",
    lifecycleStatus: "ライフサイクル状態",
    activeSecure: "稼働中＆安全",
    replaceNow: "今すぐ要更新",
    warrantyExpired: "保証期限切れ",
    settingsTitle: "将来予算計算の設定",
    resetSettings: "デフォルトに戻す",
    exportReport: "レポートを出力",
    noEntries: "財務データが見つかりません。",
    currencyLabel: "通貨",
    langLabel: "言語",
    optExcludeRetired: "除却済資産を除外",
    optStrictDep: "厳密な定額法（残存価額0%）",
    optOnlyDue: "要更新資産のみ表示",
    yearsShort: "年"
  },
  si: {
    sidebarCore: "ප්‍රධාන පුවරුව",
    sidebarOverview: "ගෝලීය දළ විශ්ලේෂණය",
    sidebarAssets: "වත්කම් ලේඛනය",
    sidebarPersonnel: "සේවක නාමාවලිය",
    sidebarUsers: "පරිශීලක ගිණුම්",
    sidebarSecurity: "සයිබර් ආරක්ෂාව (SOC)",
    sidebarCompliance: "අනුකූලතා මධ්‍යස්ථානය",
    sidebarThreats: "තර්ජන අනුකෘතිය",
    sidebarAI: "AI අවදානම් එන්ජිම",
    sidebarTracking: "ස්මාර්ට් ලුහුබැඳීම",
    sidebarLive: "සක්‍රීය උපාංග සෞඛ්‍යය",
    sidebarGeo: "GPS ස්ථාන ලුහුබැඳීම",
    sidebarQR: "QR / තීරු කේත ස්කෑන්",
    sidebarOperations: "මෙහෙයුම්",
    sidebarMaintenance: "නඩත්තු වාර්තා",
    sidebarReports: "දත්ත ලබා ගැනීම",
    sidebarAudit: "විගණන සටහන",
    sidebarSettings: "පද්ධති වින්‍යාසය",
    sidebarLogout: "සැසිය අවසන් කරන්න",
    topbarSearch: "වත්කම්, IP, හැඳුනුම්පත් සොයන්න...",
    topbarUplink: "සම්බන්ධතා තත්ත්වය",
    topbarSecure: "ආරක්ෂිතයි",
    topbarSystemAlerts: "පද්ධති අනතුරු ඇඟවීම්",
    topbarMarkRead: "සියල්ල කියවූ ලෙස සලකුණු කරන්න",
    topbarViewLogs: "සියලුම සටහන් බලන්න →",
    title: "අගය අඩුවීම සහ ප්‍රතිස්ථාපන පුරෝකථනය",
    sub: "ගතික ගණනය කිරීම්: සමාන වාර්ෂික අවප්‍රමාණය සහ ත්වරණ අවප්‍රමාණය",
    year1: "1 වන වසරේ ඇස්තමේන්තුගත ප්‍රතිස්ථාපන පිරිවැය",
    year2: "2 වන වසරේ ඇස්තමේන්තුගත ප්‍රතිස්ථාපන පිරිවැය",
    year3: "3 වන වසරේ ඇස්තමේන්තුගත ප්‍රතිස්ථාපන පිරිවැය",
    evenDecline: "සමාන වාර්ෂික අවප්‍රමාණ අගය",
    accDecline: "ත්වරණ අවප්‍රමාණ අගය",
    purchaseCost: "මිලදී ගැනීමේ පිරිවැය",
    ageLifespan: "වයස / ආයු කාලය",
    lifecycleStatus: "ජීවන චක්‍ර තත්ත්වය",
    activeSecure: "සක්‍රීය සහ ආරක්ෂිතයි",
    replaceNow: "දැන් ප්‍රතිස්ථාපනය කරන්න",
    warrantyExpired: "වගකීම් කාලය අවසන්",
    settingsTitle: "අනාගත අයවැය ගණනය කිරීම් සඳහා සැකසුම්",
    resetSettings: "පෙරනිමි සැකසුම් යළි පිහිටුවන්න",
    exportReport: "වාර්තාව අපනයනය කරන්න",
    noEntries: "මූල්‍ය වාර්තා කිසිවක් හමු නොවීය.",
    currencyLabel: "මුදල් වර්ගය",
    langLabel: "භාෂාව",
    optExcludeRetired: "අයවැය ගණනය කිරීම් වලින් විශ්‍රාමික වත්කම් ඉවත් කරන්න",
    optStrictDep: "දැඩි සරල රේඛීය අවප්‍රමාණය (0% අවම අගය සීමාව)",
    optOnlyDue: "ප්‍රතිස්ථාපනය කළ යුතු වත්කම් පමණක් පෙන්වන්න",
    yearsShort: "වසර"
  },
  ta: {
    sidebarCore: "முக்கிய பலகை",
    sidebarOverview: "உலகளாவிய மேலோட்டம்",
    sidebarAssets: "சொத்து பதிவேடு",
    sidebarPersonnel: "பணியாளர் அடைவு",
    sidebarUsers: "பயனர் கணக்குகள்",
    sidebarSecurity: "சைபர் பாதுகாப்பு (SOC)",
    sidebarCompliance: "இணக்க மையம்",
    sidebarThreats: "அச்சுறுத்தல் மேட்ரிக்ஸ்",
    sidebarAI: "AI இடர் இயந்திரம்",
    sidebarTracking: "ஸ்மார்ட் டிராக்கிங்",
    sidebarLive: "சாதன ஆரோக்கியம்",
    sidebarGeo: "GPS இருப்பிட கண்காணிப்பு",
    sidebarQR: "QR / பார் குறியீடு ஸ்கேன்",
    sidebarOperations: "செயல்பாடுகள்",
    sidebarMaintenance: "பராமரிப்பு பதிவுகள்",
    sidebarReports: "தரவு பிரித்தெடுத்தல்",
    sidebarAudit: "தணிக்கை பதிவு",
    sidebarSettings: "அமைப்பு கட்டமைப்பு",
    sidebarLogout: "அமர்வை முடிவுக்குக் கொண்டுவரவும்",
    topbarSearch: "சொத்துக்கள், IP, ஐடிகளைத் தேடுங்கள்...",
    topbarUplink: "இணைப்பு நிலை",
    topbarSecure: "பாதுகாப்பானது",
    topbarSystemAlerts: "அமைப்பு விழிப்பூட்டல்கள்",
    topbarMarkRead: "அனைத்தையும் படித்ததாகக் குறிக்கவும்",
    topbarViewLogs: "அனைத்து பதிவுகளையும் காண்க →",
    title: "மதிப்பு இழப்பு மற்றும் மாற்று முன்னறிவிப்பு",
    sub: "மாறும் கணக்கீடுகள்: சமமான ஆண்டு சரிவு மற்றும் முடுக்கப்பட்ட சரிவு",
    year1: "ஆண்டு 1 மதிப்பிடப்பட்ட மாற்றுச் செலவு",
    year2: "ஆண்டு 2 மதிப்பிடப்பட்ட மாற்றுச் செலவு",
    year3: "ஆண்டு 3 மதிப்பிடப்பட்ட மாற்றுச் செலவு",
    evenDecline: "சமமான ஆண்டு சரிவு மதிப்பு",
    accDecline: "முடுக்கப்பட்ட சரிவு மதிப்பு",
    purchaseCost: "கொள்முதல் செலவு",
    ageLifespan: "வயது / ஆயுட்காலம்",
    lifecycleStatus: "வாழ்க்கைச் சுழற்சி நிலை",
    activeSecure: "செயலில் மற்றும் பாதுகாப்பானது",
    replaceNow: "இப்போது மாற்றவும்",
    warrantyExpired: "உத்தரவாதம் முடிந்தது",
    settingsTitle: "எதிர்கால வரவுசெலவுத் திட்டக் கணக்கீடுகளுக்கான அமைப்புகள்",
    resetSettings: "இயல்புநிலை அமைப்புகளுக்கு மீட்டமைக்கவும்",
    exportReport: "அறிக்கையை ஏற்றுமதி செய்",
    noEntries: "நிதிப் பதிவுகள் எதுவும் இல்லை.",
    currencyLabel: "நாணயம்",
    langLabel: "மொழி",
    optExcludeRetired: "ஓய்வுபெற்ற சொத்துக்களை கணக்கீடுகளிலிருந்து விலக்கவும்",
    optStrictDep: "கடுமையான நேர்கோட்டு தேய்மானம் (0% மீட்பு மதிப்பு)",
    optOnlyDue: "மாற்ற வேண்டிய சொத்துக்களை மட்டும் காட்டு",
    yearsShort: "ஆண்டுகள்"
  }
};
